name: Deploy at GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      # --- Install with caching
      # https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: |
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install packages
        run: pnpm install

      - name: Check formatting
        run: pnpm format:check

      # - name: PWD
      #   run: pwd

      # - name: LS
      #   run: ls -la

      # - name: Collect artifacts
      #   id: artifact-collector
      #   run: |
      #     tar -czvf /tmp/artifacts.tar.gz ".vitepress/config.ts" "./eslintrc.js" "./prettierrc.js"

      # - name: 'Upload Artifact'
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: artifacts
      #     path: /tmp/artifacts.tar.gz
      #     retention-days: 5

      - name: Run linter
        run: pnpm lint

      # - name: Run tests
      #   run: pnpm test

      - name: Build VitePress
        run: pnpm run docs:build
        env:
          PUBLIC_PATH: /fil-docs/

      - name: Copy the static site README.md file
        run: cp static_site/README_builds.md .vitepress/dist/README.md

      - name: Push static content into fraud-intelligence-limited.github.io (main)
        working-directory: .vitepress/dist
        run: |
          git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
          git config --global user.name "${ secrets.CI_USER }"
          git config --global init.defaultBranch main
          git init
          git add --all
          git commit -m "Auto update pages on $(date +'%Y-%m-%d %H:%M:%S')"
          git push -f -q https://${{ secrets.CI_USER }}:${{ secrets.CI_TOKEN }}@github.com/fraud-intelligence-limited/fraud-intelligence-limited.github.io.git main
